table _Measures

	column _dummy
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: [_dummy]

	measure 'Total Hectolitres' = SUM(Sales[Hectolitres])
		formatString: #,0

	measure 'Turnover' = SUM(Sales[Turnover])
		formatString: #,0

	measure 'Hectolitres LY' = CALCULATE([Total Hectolitres], SAMEPERIODLASTYEAR(Calendar[Date]))
		formatString: #,0

	measure 'Turnover LY' = CALCULATE([Turnover], SAMEPERIODLASTYEAR(Calendar[Date]))
		formatString: #,0

	measure 'Hectolitres YoY %' = DIVIDE([Total Hectolitres] - [Hectolitres LY], [Hectolitres LY])
		formatString: #,0

	measure 'Avg Turnover per HL' = DIVIDE([Turnover], [Total Hectolitres])
		formatString: #,0

	partition _Measures = calculated
		mode: import
		source = Row("_dummy", BLANK())
