table _Measures

	measure 'Total Sales' = SUM(FactSales[Amount])
		formatString: 0

	measure 'Total Quantity' = SUM(FactSales[Quantity])
		formatString: 0

	measure 'Avg Price' = DIVIDE([Total Sales], [Total Quantity])
		formatString: 0

	measure 'Sales LY' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR(DimDate[Date]))
		formatString: 0

	measure 'Sales YoY %' = DIVIDE([Total Sales] - [Sales LY], [Sales LY])
		formatString: 0
