table _Measures

	measure 'Total Sales' = ROUND(SUM(FactSales[Amount]), 0)
		formatString: 0

	measure 'Total Quantity' = SUM(FactSales[Quantity])
		formatString: 0

	measure 'Avg Price' = ROUND(DIVIDE([Total Sales], [Total Quantity]), 2)
		formatString: 0

	measure 'Sales LY' = CALCULATE([Total Sales], SAMEPERIODLASTYEAR(DimDate[Date]))
		formatString: 0

	measure 'Sales YoY %' = DIVIDE([Total Sales] - [Sales LY], [Sales LY])
		formatString: 0
