table _Measures

	measure 'Revenue' = SUM(Sales[Revenue])
		formatString: 0

	measure 'Units' = SUM(Sales[Units])
		formatString: 0

	measure 'Avg Price' = DIVIDE([Revenue], [Units])
		formatString: 0

	measure 'Revenue LY' = CALCULATE([Revenue], SAMEPERIODLASTYEAR(Calendar[Date]))
		formatString: 0

	measure 'Revenue YoY %' = DIVIDE([Revenue] - [Revenue LY], [Revenue LY])
		formatString: 0
